### PR TITLE
Centralize the test runner

### PR DESCRIPTION
**Pull request by verbosus**
This proposal fixes LettError/MutatorMath#69 by introducing a centralized test runner. 

To make this possible, I moved some doctests around. The ones that used to be in objects/location.py and objects/mutator.py inside docstrings in functions inside `if __name__ == '__main__':` have now been moved to test/objects/location.py and test/objects/mutator.py. Both can be run indvidually as doctets runners as before, but also contribute to the overall test suite now.

The preferred way of running the tests is now `python Lib/mutatorMath/test/run.py` but it is also possible to run each file individually as before, and the doctests for that particular file will be exercised. This commit also fixes some issues in the test data, like the lowercase x in the LightWide.ufo master not being point-compatible with the other masters.

### CODE REVIEW

**Comment by verbosus** [comment]
Hang on, investigating the failure on the Travis environment.

**Comment by verbosus** [comment]
Not sure what’s happening, I followed the Travis steps (cloning master, fetching my pull branch, merging) and can build just fine on my machine both on Python 2 and Python 3.

**Comment by miguelsousa** [comment]
@verbosus just in case you didn't see it
Python 2.7 is failing with
```python
Traceback (most recent call last):
  File "Lib/mutatorMath/test/run.py", line 5, in <module>
    import mutatorMath.test.objects.mutator
ImportError: No module named test.objects.mutator
```

and Python 3.5 is failing with
```python
Traceback (most recent call last):
  File "Lib/mutatorMath/test/run.py", line 5, in <module>
    import mutatorMath.test.objects.mutator
ImportError: No module named 'mutatorMath.test'
```

**Comment by verbosus** [comment]
Not for me on Python 2.7.10 nor 3.6. Still digging…

**Comment by verbosus** [comment]
@miguelsousa does the failure reproduce consistently for you? If so, are you on the merged repo between master and my pull request, on my branch or elsewhere? How is your mutatorMath installed? Where are you calling mutatorMath/test/run.py from? Anything that helps me reproduce the Traceback you‘re seeing would be appreciated.

**Comment by anthrotype** [comment]
@verbosus I've fixed the issue with `python setup.py test` printing a traceback on exit when running on py27. The issue was in the "last resort" logging handler of `fonttools.misc.py23`.
Read here for more info:
https://github.com/fonttools/fonttools/commit/972b3e6a156157e2f68c47dfff784419658cf556

I'll tag a 3.6.1 release soon.
@verbosus Can you please check that when using fonttools from master, the `python setup.py test` no longer raises that AttributeError exception?

I'll have a look at the rest of the PR after lunch, thanks.

**Comment by verbosus** [comment]
`python setup.py test` now works for me on fonttools master on Python 2.7.10, thanks. @anthrotype do you have any idea of what’s happening with Travis? I cannot reproduce it at all on my machine.

**Comment by anthrotype** [comment]
I'm investigating. In the meantime, can you try to rebase the current PR on the latest master, and remove commit 9b94bae as that was already merged along with PR #68?

**Comment by anthrotype** [comment]
I've tagged [fonttools 3.6.1](https://github.com/fonttools/fonttools/releases/tag/3.6.1), so you may want to also update the MutatorMath's requirements.txt to use it:

```diff
diff --git a/requirements.txt b/requirements.txt
index 03b49f8..26fe0c3 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-fonttools==3.3.0
+fonttools==3.6.1
 ufoLib==2.0.0
 defcon==0.2.0
 fontMath==0.4.1
```

**Comment by anthrotype** [comment]
I've cherry-picked 01820c2fbeb9f4c7d1b97c79306aeb37f9603369 and bumped fonttools==3.6.1 in this branch on my fork:
https://travis-ci.org/anthrotype/MutatorMath/builds/196166121

The python2.7 tests now pass while the 3.5 ones have one failure which you may want to investigate.

If we use `python setup.py test` to run the test suite, we don't need to also install MutatorMath because the `PYTHONPATH` is temporarily modified by the setuptools test runner to import mutatorMath from "Lib/".

So you can remove the line `pip install -v .` inside the `.travis.yml` file.

The `ImportError` issue you were having early on had to do with the fact that we don't install the `mutatorMath.test` sub-package (see the list of `packages` in `setup.py`), but coverage was running the `test.py` module against the installed mutatorMath.

I personally prefer when the tests are located in an external folder outside the actual package. It makes everything easier, and avoids this tricky issues. Even more so considering that mutatorMath already excludes the tests from the installed package.

**Comment by anthrotype** [comment]
in case you didn't know, you can push a different local branch to an existing remote branch. This way you can rebase and clean up the merge conflict, and then push to the same PR without having to open a new PR:

```sh
git push -f origin local-branch-name:remote-branch-name
```

**Comment by verbosus** [comment]
Almost there. As far as I can tell, the failure on Python 3 is due to the change in fontMath. MutatorMath’s behavior and test depend on the old behavior of `__cmp__`. Indeed, implementing a `__lt__` that is exactly like the old `__cmp__` makes the problem go away. For now we could either comment the mutatorMath test until a fix lands in fontMath, or just wait to merge this pull request. And here’s the failure:
```
======================================================================
FAIL: test1 (mutatorMath.test.ufo.geometryTest)
Doctest: mutatorMath.test.ufo.geometryTest.test1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for mutatorMath.test.ufo.geometryTest.test1
  File "/Users/verbosus/Environments/fonttools/src/mutatormath/Lib/mutatorMath/test/ufo/geometryTest.py", line 133, in test1

----------------------------------------------------------------------
File "/Users/verbosus/Environments/fonttools/src/mutatormath/Lib/mutatorMath/test/ufo/geometryTest.py", line 137, in mutatorMath.test.ufo.geometryTest.test1
Failed example:
    testGeometry(os.path.join(os.getcwd(), "testData"), cleanUp=False)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest mutatorMath.test.ufo.geometryTest.test1[2]>", line 1, in <module>
        testGeometry(os.path.join(os.getcwd(), "testData"), cleanUp=False)
      File "/Users/verbosus/Environments/fonttools/src/mutatormath/Lib/mutatorMath/test/ufo/geometryTest.py", line 119, in testGeometry
        assert r2['glyphOne'].bounds == (0, 0, 100, 500)
    AssertionError
```

**Comment by anthrotype** [comment]
No, it can't be the change in fontMath. We haven't tagged a new release yet, and .travis.yml is configured to pip install -r requirements.txt, which specifies `fontMath==0.4.1`.

Tomorrow I'll try to add an `__lt__` method to fontMath's MathGlyph and see if that fixes the issue.

But before we merge, I think you should squash the commits on this branch, otherwise the git log gets a bit confusing.

Thanks!

**Comment by anthrotype** [comment]
https://github.com/LettError/MutatorMath/commit/c0c462edf694b82d7a731a0418cd7669ff792d73 should fix the issue with sorting MathGlyph instances.

@verbosus can you clean up this branch? Only the commits "Centralized test runner" and "Updating requirements.txt to fonttools 3.6.1" should be present. After that we can merge and tag a new release.

btw, 85 % of test coverage is not bad!

**Comment by verbosus** [comment]
Aaaaand we’re done!

**Comment by anthrotype** [comment]
Thanks!

**Pull request merged**
