### PR TITLE
Removing robofab from travis.yml

### PR DESCRIPTION
**Pull request by benkiel**
Should not be necessary anymore, but CI will tell us if it all comes crumbling down.

### CODE REVIEW

**Comment by benkiel** [comment]
Hmm, not sure why this failed, the Travis message isn't clear at all.

**Comment by LettError** [comment]
Maybe something to do with the pens?

**Comment by anthrotype** [comment]
it's weird. Travis couldn't even generate the build script, as if the YAML was not properly formatted. Though it looks fine to me. @LettError could you maybe try re-running the build (you can click on the "refresh" button on the MutatorMath Travis page?

**Comment by anthrotype** [comment]
it works! 🎉

**Comment by LettError** [comment]
No more robofab.

**Comment by typemytype** [comment]
😢

gr Frederik
www.typemytype.com

**Pull request merged**
