### PR TITLE
don't bend sources/instances locations by default

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlefonts/fontmake/pull/552

Masters locations are always assumed to be specified in internal, design coordinates thus already mapped and not needing to be "bent" using the avar-style axes mappings.

Similarly, instance locations are also assumed to be specified in internal design coordinates by default (the default value for `bend` argument of `Mutator.makeInstance` was flipped to `False`).

A new `bendLocations` option is added to `build` method (and DesignSpaceDocumentReader) to allow to interpret instance locations as being defined in _user_-space coordinate system, thus requiring to be "bent" using the provided axes mappings.

This is a "bugfix" however it's difficult to introduce it in a backward compatible way.. 
The old behaviour (where _both_ masters and instances' locations were understood as being specified in _user_ space locations and were thus warped by the Bender using axis mapping) simply is incompatible with the way the same data has been interpreted by the other major consumer of designspaces (fontTools.varLib), as I explained in the linked fontmake issue.

I suggest bumping the major version of MutatorMath to 3.0 and call it a day.

Note: I haven't tested what effect this changes will produce on ufoProcessor.

@LettError I'll leave it to you to decide what to do from here.

Even if this PR isn't going merged, I am leaning towards merging the hack-ish workaround that I propsed in https://github.com/googlefonts/fontmake/pull/552 (where I make a temporary copy of the input designspace file without the axes map elements to prevent MutatorMath from distorting the masters/instances locations).

### CODE REVIEW

**Comment by LettError** [comment]
@miguelsousa Are you ok with these changes?

**Comment by LettError** [comment]
Running the mutatormath tests. This is not a very helpful report. 
```----------------------------------------------------------------------
Ran 48 tests in 0.744s

OK
Traceback (most recent call last):
  File "/Users/erik/code/MutatorMath/Lib/mutatorMath/test/run.py", line 53, in <module>
    sys.exit(unittest.main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 258, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: False
>>> 

```
I imagine that before this becomes a release, the tests would have to work. I didn't write the current test setup, and I don't have the time this week to find out how it works.

**Comment by anthrotype** [comment]
hm strange... but they did pass on my machine when I run tox, and also on the Travis CI.

**Comment by anthrotype** [comment]
can you try to run `git clean -fdx .` on your repo (dangerous!) or clone to a different folder and try to run the tests again. Might be some untracked files left over..

**Comment by miguelsousa** [comment]
@LettError I am if you are.

**Comment by anthrotype** [comment]
Thanks @LettError. Shall I tag version 3.0.0 given this is a breaking change?

**Pull request merged**
