### PR TITLE
set up PyPI deployment

### PR DESCRIPTION
**Pull request by anthrotype**
Hi Erik,

I would like to have MutatorMath available on PyPI so other applications such as fontmake can require it more easily, without having to clone the git repository.

I'm using my encrypted PyPI credentials, but I can give you admin access to the PyPI account if you let me know your PyPI user name.

I bumped the package version to 2.0.0, as it's been 1.8 since a while now, and things have changed a lot since then.

I also converted the README to reStructuredText format, as markdown is not supported on PyPI yet (the setup.py `long_description` is read from the README.rst, and will be used as the PyPI package home page).

If you give me push access to the repo, I can help you tagging new releases like I'm doing with the rest of the font tools stack.

Anyway, the release process should be straightforward. You simply need to manually update the package version in both `setup.py` and `mutatorMath/__init__.py`, and then create a git tag and push it to the remote repository.

Travis will then take care of building the source and wheel distribution packages, and upload them to PyPI.

Let me know if this is ok.
Thank you

Cosimo

### CODE REVIEW

**Comment by LettError** [comment]
Hi Cosimo,
Thank you for offering to do this! I don't have any experience in that area. 

Would this make a difference for adding code? 

I'm traveling this week, will try to look at it!

Erik

**Comment by anthrotype** [comment]
> Would this make a difference for adding code?

Sorry, I'm not quite sure what you mean.

The changes in this PR only add some metadata-related stuff to comply with PyPI requirements, and to produce correct sdist and wheel packages for upload. It also configures Travis CI to do the uploading automatically when a git tag is pushed. That's it.

You can continue modifying the source code as you normally do. Then when you think things are ready for a new release, you bump the package version, push a tag and Travis takes care of the rest.

Easy peasy! :)

Please let me know if you have any questions. I can explain in more details if you need.

**Comment by anthrotype** [comment]
pretty-ping! :)

**Comment by anthrotype** [comment]
Thanks! Feel free to make a GitHub Release whenever you feel ready. Everything should work now. :)

**Comment by LettError** [comment]
Done, I think. Thanks!

**Comment by anthrotype** [comment]
It's live!
https://pypi.python.org/pypi/MutatorMath

Go `pip install MutatorMath` everyone!

**Pull request merged**
