### PR TITLE
Change travis to unified-font-object ufoLib.

### PR DESCRIPTION
**Pull request by LettError**

### CODE REVIEW

**Comment by behdad** [comment]
You should use requirements.txt and `pip install -r requirements.txt` instead.

**Comment by LettError** [comment]
Behdad, the tests in this branch are failing and they should not. I'm also not sure what your comment means.

**Comment by miguelsousa** [comment]
@LettError it's failing with `ImportError: No module named robofab.pens.adapterPens` which is used by `defcon/pens/decomposeComponentPointPen.py` it seems. Perhaps it's `defcon` that needs to be updated.

**Comment by LettError** [comment]
It was an experiment to see if I could remove the robofab dependency. I suppose it is waiting on the pens. This branch can go.

**Comment by adrientetar** [comment]
defcon needs a few minor changes to let go of robofab. Give me a few days to sort this out, my fork is already patched.

**Comment by behdad** [comment]
> Behdad, the tests in this branch are failing and they should not. I'm also not sure what your comment means.

My comment was tangential.  I meant that for installing dependencies, it's easier if you add a requirements.txt file with all dependencies and use `pip` to install them with a single command.

**Comment by LettError** [comment]
I'll wait until some of the dust on ufolib and friends settle.

**Comment by adrientetar** [comment]
I'm confused, doesn't [this patch](https://github.com/typesupply/defcon/pull/35) solve the error that occured here? I would try restarting the Travis worker.

**Comment by adrientetar** [comment]
Oh I see it leaves some pen dependency. My bad.

**Pull request closed without merging**
