### PR TITLE
Allow multiple unicode values for glyphs

### PR DESCRIPTION
**Pull request by khaledhosny**
Fixes https://github.com/LettError/MutatorMath/issues/85

### CODE REVIEW

**Comment by khaledhosny** [comment]
Not sure if this breaks public API, if so we probably need to keep `unicodeValue` and provide another `unicodes` keyword argument similar to defcon. Also I think the old code was trying to detect different unicode values accross masters, which is probably not detected now.

**Comment by anthrotype** [comment]
the designSpaceDocument's specification should probably be modified as well to allow a list of unicode values for each glyph element, rather than a single one:

https://github.com/LettError/designSpaceDocument#attributes-7

**Comment by anthrotype** [comment]
@khaledhosny @LettError so, does this change the attributes of `glyph` element (from `unicode` to `unicodes`) in the generated designspace? Shouldn't it be reflected in the spec?

btw, the `designSpaceDocument` still uses the old `unicodeValue`:
https://github.com/LettError/designSpaceDocument/blob/master/Lib/designSpaceDocument/__init__.py#L897-L900

**Comment by LettError** [comment]
Thanks @anthrotype, guess I'll need to fix that.

**Comment by LettError** [comment]
I _think_ I made all the right changes to support multiple unicode values in the `glyph` element in designSpaceDocument. Tests added.
https://github.com/LettError/designSpaceDocument/compare/unicodes

**Pull request merged**
